-- A newer real case export surfaced a 6th phase not seen in migration 010's source
-- data: 'Rejected' — the back office rejected the FE's submission for a component,
-- which needs FE rework (unlike Uploaded/Accept-Approve/Stop, which are terminal for
-- the FE). See generate-real-case-seed.mjs's TERMINAL_/REWORK_ACTION_STATUS_CODES.
INSERT OR IGNORE INTO dropdown_options (id, category, code, label, sort_order) VALUES
  ('as-rejected', 'action_status', 'rejected', 'Rejected', 4);

-- Migration 010's CSV parser left a stray leading '=' (Excel's cell-formula escape) in
-- `cases.primary_contact_number`/`secondary_contact_number` whenever the source CSV's
-- Contact Number cell held a single quoted number (e.g. ="7093971435") rather than the
-- more common "num1 / num2" format. Unused by the API (only the pre-masked phone columns
-- on case_components are ever returned), but worth cleaning up since it's cheap here.
UPDATE cases SET primary_contact_number = LTRIM(primary_contact_number, '=') WHERE primary_contact_number LIKE '=%';
UPDATE cases SET secondary_contact_number = LTRIM(secondary_contact_number, '=') WHERE secondary_contact_number LIKE '=%';

-- Generated by:
--   node scripts/generate-real-case-seed.mjs <csv-dir> src/db/migrations/011_add_rejected_action_status.sql Rejected:rejected
-- (appended by hand after the dropdown_options insert above; do not hand-edit the
-- INSERTs below — regenerate them from the source CSV instead)

INSERT OR IGNORE INTO cases (id, case_ref, client_name, candidate_name, profile_status, primary_contact_number, secondary_contact_number) VALUES
  ('case-real-quath00000105', 'QUATH00000105', 'Qualitest', 'test case 24 jan kalitthkar', 'interim_report_generated', '9866867776', '9866867776'),
  ('case-real-apex00000003', 'APEX00000003', 'Apexon Technologies', 'srinivas malladi', 'bgv_profile_created', '7093971435', '7093971435');

INSERT OR IGNORE INTO case_components (
  id, case_id, component_status, action_status, bucket, verification_type, address_type, residence_type, address, location,
  remarks, additional_verification_instructions, additional_verification_remarks, assigned_to_name, tat_due_at,
  masked_primary_phone, masked_secondary_phone, received_date, action_updated_date, insuff_raised_date,
  insuff_cleared_date, addl_doc_requested_date, addl_doc_cleared_date, cost_approval_requested_date,
  cost_approved_date, cost_rejected_date, cost_currency, cost_amount
) VALUES
  ('comp-quath00000105-rejected-1', 'case-real-quath00000105', 'new_component', 'rejected', 'beyond_tat', 'Permanent Address', 'permanent', 'rented', '1-2 ,hjejfjj ,jhbjfjej ,bfjbjfj ,jbfjbjfj ,300047', 'jhbjfjej', 'component createdtest', '', '', '', '2026-01-31 18:00:00', '+91-9XXXXX7776', '+91-9XXXXX7776', '2026-01-24', '2026-01-26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('check-15061424', 'case-real-apex00000003', 'new_component', 'rejected', 'beyond_tat', 'Permanent Address', 'permanent', 'owned', 'Bangalore ,- ,- ,- ,-', '-', 'component created', '', '', '', '2025-04-04 18:00:00', '+91-7XXXXX1435', '+91-7XXXXX1435', NULL, '2026-01-26', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
